//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingRejser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilmeldinger
    {
        public int Id { get; set; }
        public int Rejsearrangement { get; set; }
        public int Kunde { get; set; }
    
        public virtual Kunder Kunder { get; set; }
        public virtual Rejsearrangementer Rejsearrangementer { get; set; }
    }
}
